STARTUP_OPERATION_ID = "podping-startup"

STARTUP_FAILED_UNKNOWN_EXIT_CODE = 10
STARTUP_FAILED_INVALID_POSTING_KEY_EXIT_CODE = 20
STARTUP_FAILED_HIVE_API_ERROR_EXIT_CODE = 30

SERVER_ACCOUNT_NOT_AUTHORISED_TO_PODPING = 40
